project:
  type: website
  output-dir: docs
  
website:
  title: "Sequoia Fellenbaum Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"      
      - href: Land-To-Sea.qmd
        text: "Land To Sea Analysis"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

